package musicStreaming.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_MusicGenre extends EnumerationDescriptorBase {

  public EnumerationDescriptor_MusicGenre() {
    super(0x79d092ed8c7a4027L, 0x98a46148912f43e1L, 0x74e6b04ad8bac99eL, "MusicGenre", "r:3a7149cd-01af-4c52-9ee9-1b272990cfb7(musicStreaming.structure)/8423613988553279902");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Pop_0 = new EnumerationDescriptor.MemberDescriptor("Pop", "Pop", 0x74e6b04ad8bac99fL, "r:3a7149cd-01af-4c52-9ee9-1b272990cfb7(musicStreaming.structure)/8423613988553279903");
  private final EnumerationDescriptor.MemberDescriptor myMember_Rock_0 = new EnumerationDescriptor.MemberDescriptor("Rock", "Rock", 0x74e6b04ad8bac9a0L, "r:3a7149cd-01af-4c52-9ee9-1b272990cfb7(musicStreaming.structure)/8423613988553279904");
  private final EnumerationDescriptor.MemberDescriptor myMember_Afrobeats_0 = new EnumerationDescriptor.MemberDescriptor("Afrobeats", "Afrobeats", 0x74e6b04ad8bac9a1L, "r:3a7149cd-01af-4c52-9ee9-1b272990cfb7(musicStreaming.structure)/8423613988553279905");
  private final EnumerationDescriptor.MemberDescriptor myMember_Hiphop_0 = new EnumerationDescriptor.MemberDescriptor("Hiphop", "Hiphop", 0x74e6b04ad8bac9a2L, "r:3a7149cd-01af-4c52-9ee9-1b272990cfb7(musicStreaming.structure)/8423613988553279906");
  private final EnumerationDescriptor.MemberDescriptor myMember_Rhythm_and_blues_0 = new EnumerationDescriptor.MemberDescriptor("Rhythm_and_blues", "Rhythm_and_blues", 0x74e6b04ad8bac9a3L, "r:3a7149cd-01af-4c52-9ee9-1b272990cfb7(musicStreaming.structure)/8423613988553279907");
  private final EnumerationDescriptor.MemberDescriptor myMember_Jazz_0 = new EnumerationDescriptor.MemberDescriptor("Jazz", "Jazz", 0x74e6b04ad8bac9a5L, "r:3a7149cd-01af-4c52-9ee9-1b272990cfb7(musicStreaming.structure)/8423613988553279909");
  private final EnumerationDescriptor.MemberDescriptor myMember_Country_0 = new EnumerationDescriptor.MemberDescriptor("Country", "Country", 0x74e6b04ad8bac9a6L, "r:3a7149cd-01af-4c52-9ee9-1b272990cfb7(musicStreaming.structure)/8423613988553279910");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x79d092ed8c7a4027L, 0x98a46148912f43e1L, 0x74e6b04ad8bac99eL, 0x74e6b04ad8bac99fL, 0x74e6b04ad8bac9a0L, 0x74e6b04ad8bac9a1L, 0x74e6b04ad8bac9a2L, 0x74e6b04ad8bac9a3L, 0x74e6b04ad8bac9a5L, 0x74e6b04ad8bac9a6L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Pop_0, myMember_Rock_0, myMember_Afrobeats_0, myMember_Hiphop_0, myMember_Rhythm_and_blues_0, myMember_Jazz_0, myMember_Country_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_Afrobeats_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Pop":
        return myMember_Pop_0;
      case "Rock":
        return myMember_Rock_0;
      case "Afrobeats":
        return myMember_Afrobeats_0;
      case "Hiphop":
        return myMember_Hiphop_0;
      case "Rhythm_and_blues":
        return myMember_Rhythm_and_blues_0;
      case "Jazz":
        return myMember_Jazz_0;
      case "Country":
        return myMember_Country_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
