package musicStreaming.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Order extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Order() {
    super(0x79d092ed8c7a4027L, 0x98a46148912f43e1L, 0x74e6b04ad8bac9d2L, "Order", "r:3a7149cd-01af-4c52-9ee9-1b272990cfb7(musicStreaming.structure)/8423613988553279954");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_added_date_0 = new EnumerationDescriptor.MemberDescriptor("added_date", "added_date", 0x74e6b04ad8bac9d3L, "r:3a7149cd-01af-4c52-9ee9-1b272990cfb7(musicStreaming.structure)/8423613988553279955");
  private final EnumerationDescriptor.MemberDescriptor myMember_duration_0 = new EnumerationDescriptor.MemberDescriptor("duration", "duration", 0x74e6b04ad8bac9d4L, "r:3a7149cd-01af-4c52-9ee9-1b272990cfb7(musicStreaming.structure)/8423613988553279956");
  private final EnumerationDescriptor.MemberDescriptor myMember_custom_order_0 = new EnumerationDescriptor.MemberDescriptor("custom_order", "custom_order", 0x74e6b04ad8bac9d5L, "r:3a7149cd-01af-4c52-9ee9-1b272990cfb7(musicStreaming.structure)/8423613988553279957");
  private final EnumerationDescriptor.MemberDescriptor myMember_artist_0 = new EnumerationDescriptor.MemberDescriptor("artist", "artist", 0x74e6b04ad8bac9d6L, "r:3a7149cd-01af-4c52-9ee9-1b272990cfb7(musicStreaming.structure)/8423613988553279958");
  private final EnumerationDescriptor.MemberDescriptor myMember_title_0 = new EnumerationDescriptor.MemberDescriptor("title", "title", 0x74e6b04ad8bac9d7L, "r:3a7149cd-01af-4c52-9ee9-1b272990cfb7(musicStreaming.structure)/8423613988553279959");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x79d092ed8c7a4027L, 0x98a46148912f43e1L, 0x74e6b04ad8bac9d2L, 0x74e6b04ad8bac9d3L, 0x74e6b04ad8bac9d4L, 0x74e6b04ad8bac9d5L, 0x74e6b04ad8bac9d6L, 0x74e6b04ad8bac9d7L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_added_date_0, myMember_duration_0, myMember_custom_order_0, myMember_artist_0, myMember_title_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_added_date_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "added_date":
        return myMember_added_date_0;
      case "duration":
        return myMember_duration_0;
      case "custom_order":
        return myMember_custom_order_0;
      case "artist":
        return myMember_artist_0;
      case "title":
        return myMember_title_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
