package musicStreaming.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_podcastType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_podcastType() {
    super(0x79d092ed8c7a4027L, 0x98a46148912f43e1L, 0x74e6b04ad8bac9c5L, "podcastType", "r:3a7149cd-01af-4c52-9ee9-1b272990cfb7(musicStreaming.structure)/8423613988553279941");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_career_0 = new EnumerationDescriptor.MemberDescriptor("career", "career", 0x74e6b04ad8bac9c6L, "r:3a7149cd-01af-4c52-9ee9-1b272990cfb7(musicStreaming.structure)/8423613988553279942");
  private final EnumerationDescriptor.MemberDescriptor myMember_politics_0 = new EnumerationDescriptor.MemberDescriptor("politics", "politics", 0x74e6b04ad8bac9c7L, "r:3a7149cd-01af-4c52-9ee9-1b272990cfb7(musicStreaming.structure)/8423613988553279943");
  private final EnumerationDescriptor.MemberDescriptor myMember_film_0 = new EnumerationDescriptor.MemberDescriptor("film", "film", 0x74e6b04ad8bac9c8L, "r:3a7149cd-01af-4c52-9ee9-1b272990cfb7(musicStreaming.structure)/8423613988553279944");
  private final EnumerationDescriptor.MemberDescriptor myMember_tv_0 = new EnumerationDescriptor.MemberDescriptor("tv", "tv", 0x74e6b04ad8bac9c9L, "r:3a7149cd-01af-4c52-9ee9-1b272990cfb7(musicStreaming.structure)/8423613988553279945");
  private final EnumerationDescriptor.MemberDescriptor myMember_health_0 = new EnumerationDescriptor.MemberDescriptor("health", "health", 0x74e6b04ad8bac9caL, "r:3a7149cd-01af-4c52-9ee9-1b272990cfb7(musicStreaming.structure)/8423613988553279946");
  private final EnumerationDescriptor.MemberDescriptor myMember_technology_0 = new EnumerationDescriptor.MemberDescriptor("technology", "technology", 0x74e6b04ad8bac9cbL, "r:3a7149cd-01af-4c52-9ee9-1b272990cfb7(musicStreaming.structure)/8423613988553279947");
  private final EnumerationDescriptor.MemberDescriptor myMember_travel_0 = new EnumerationDescriptor.MemberDescriptor("travel", "travel", 0x74e6b04ad8bac9ccL, "r:3a7149cd-01af-4c52-9ee9-1b272990cfb7(musicStreaming.structure)/8423613988553279948");
  private final EnumerationDescriptor.MemberDescriptor myMember_lifestyle_0 = new EnumerationDescriptor.MemberDescriptor("lifestyle", "lifestyle", 0x74e6b04ad8bac9cdL, "r:3a7149cd-01af-4c52-9ee9-1b272990cfb7(musicStreaming.structure)/8423613988553279949");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x79d092ed8c7a4027L, 0x98a46148912f43e1L, 0x74e6b04ad8bac9c5L, 0x74e6b04ad8bac9c6L, 0x74e6b04ad8bac9c7L, 0x74e6b04ad8bac9c8L, 0x74e6b04ad8bac9c9L, 0x74e6b04ad8bac9caL, 0x74e6b04ad8bac9cbL, 0x74e6b04ad8bac9ccL, 0x74e6b04ad8bac9cdL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_career_0, myMember_politics_0, myMember_film_0, myMember_tv_0, myMember_health_0, myMember_technology_0, myMember_travel_0, myMember_lifestyle_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_lifestyle_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "career":
        return myMember_career_0;
      case "politics":
        return myMember_politics_0;
      case "film":
        return myMember_film_0;
      case "tv":
        return myMember_tv_0;
      case "health":
        return myMember_health_0;
      case "technology":
        return myMember_technology_0;
      case "travel":
        return myMember_travel_0;
      case "lifestyle":
        return myMember_lifestyle_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
